# startup: `docker compose up -d`
# check: `docker compose ps` / `docker compose logs -f`

services:
  timescaledb:
    image: ${TIMESCALE_IMAGE}
    container_name: ${TIMESCALE_NAME}
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/pgdata
    volumes:
      - "${PGDATA_DIR}:/pgdata"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres || exit 1"]
      interval: 5s
      timeout: 4s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  banbot:
    image: banbot/banbot:${BANBOT_TAG}
    # platform: linux/amd64  # 如果是arm架构CPU，需取消注释此行，否则会错误：no matching manifest for linux/arm64
    container_name: ${BANBOT_NAME}
    ports:
      - "${BANBOT_PORT}:8000"
    command:
      - -host
      - 0.0.0.0
      - -config-data
      - |
        database:
          url: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@timescaledb:5432/ban
        exchange:
          binance:
            proxy: ${BANBOT_PROXY}
    volumes:
      - "${BANBOT_DIR}:/ban/strats"
      - "${BANBOT_DATA}:/ban/data"
    depends_on:
      timescaledb:
        condition: service_healthy
    restart: unless-stopped